- name: Install Package httpd for Redhat
  yum:
    name: httpd
- name: Install Package php redhat
  yum:
    name: php, php-mysql, php-gd, php-mbstring
- name: Check Httpd Service
  service:
    name: httpd
    state: started
    enabled: yes
